//! Wire contract endpoint-service → backend-service.
//!
//! The schema source of truth is `../wire.proto` (`package edr.wire.v1`); Rust
//! message types are generated by `prost-build` at compile time (see `build.rs`,
//! protoc is vendored) and exposed under [`pb`]. This module adds:
//!
//!  * the public API [`encode_frame`]/[`decode_frame`] — the **TCP framing**
//!    (`Len:u32le (payload only) ++ payload`, see wire.proto header), needed
//!    because protobuf messages are not self-delimiting on a stream;
//!  * the conversion layer [`pb`] ⇄ `edr_engine::wire` types, so the services and
//!    the engine keep using the plain in-process types and only this crate
//!    depends on prost.
//!
//! The bare-payload codec (`encode_wire`/`decode_wire`) is a private inner layer
//! of the frame; callers only ever deal in frames.
//!
//! Decoding validates what proto3 cannot express: the `Wire`/`NodeKey` oneofs
//! must be set, `Event.actor`/`object`/`event` must be present, and `Op` must be
//! a known non-`OP_UNSPECIFIED` value.

use edr_engine::wire::{BlockReport, Wire, WireEvent};
use edr_engine::{Attrs, Event, NodeKey, Op};
use prost::Message;
use std::collections::BTreeMap;

/// Generated protobuf types for `package edr.wire.v1` (source: `wire.proto`).
pub mod pb {
    include!(concat!(env!("OUT_DIR"), "/edr.wire.v1.rs"));
}

// ---- public API --------------------------------------------------------------

/// Encode one record as a length-prefixed frame ready for the TCP stream.
pub fn encode_frame(w: &Wire) -> Vec<u8> {
    let p = encode_wire(w);
    let mut out = Vec::with_capacity(4 + p.len());
    out.extend_from_slice(&(p.len() as u32).to_le_bytes());
    out.extend_from_slice(&p);
    out
}

/// Decode the first complete frame in `buf`. Returns `Ok(None)` when more bytes
/// are needed, `Ok(Some((wire, consumed)))` on success, `Err` on a malformed frame.
pub fn decode_frame(buf: &[u8]) -> Result<Option<(Wire, usize)>, String> {
    if buf.len() < 4 {
        return Ok(None);
    }
    let len = u32::from_le_bytes([buf[0], buf[1], buf[2], buf[3]]) as usize;
    if buf.len() < 4 + len {
        return Ok(None);
    }
    let wire = decode_wire(&buf[4..4 + len])?;
    Ok(Some((wire, 4 + len)))
}

/// Encode a bare `edr.wire.v1.Wire` message (no frame prefix). Internal: callers
/// use [`encode_frame`]; the bare payload is only the inner layer of a frame.
fn encode_wire(w: &Wire) -> Vec<u8> {
    pb_wire(w).encode_to_vec()
}

/// Decode a bare `edr.wire.v1.Wire` message (no frame prefix). Internal: callers
/// use [`decode_frame`], which strips the length prefix first.
fn decode_wire(b: &[u8]) -> Result<Wire, String> {
    let m = pb::Wire::decode(b).map_err(|e| format!("Wire: {}", e))?;
    wire_from_pb(m)
}

// ---- edr_engine::wire → pb -----------------------------------------------

fn pb_wire(w: &Wire) -> pb::Wire {
    let msg = match w {
        Wire::Event(we) => pb::wire::Msg::Event(pb::WireEvent {
            seq: we.seq,
            endpoint_sid: we.endpoint_sid as u64,
            ttps: we.ttps.clone(),
            event: Some(pb_event(&we.event)),
        }),
        Wire::Block(br) => pb::wire::Msg::Block(pb::BlockReport {
            seq: br.seq,
            pattern: br.pattern.clone(),
            score: br.score,
            reason: br.reason.clone(),
            event: Some(pb_event(&br.event)),
        }),
    };
    pb::Wire { msg: Some(msg) }
}

fn pb_event(e: &Event) -> pb::Event {
    pb::Event {
        ts: e.ts,
        op: pb_op(e.op) as i32,
        actor: Some(pb_key(&e.actor)),
        object: Some(pb_key(&e.object)),
        attrs: pb_attrs(&e.attrs),
    }
}

/// Flatten the typed `Attrs` back into the wire's `map<string,string>` (only set
/// fields are emitted), preserving the on-the-wire contract with the backend.
fn pb_attrs(a: &Attrs) -> BTreeMap<String, String> {
    let mut m = BTreeMap::new();
    if let Some(v) = &a.image {
        m.insert("image".to_string(), v.clone());
    }
    if let Some(v) = &a.cmd {
        m.insert("cmd".to_string(), v.clone());
    }
    if let Some(v) = &a.target_image {
        m.insert("target_image".to_string(), v.clone());
    }
    if let Some(v) = &a.dir {
        m.insert("dir".to_string(), v.clone());
    }
    if let Some(v) = a.entropy {
        m.insert("entropy".to_string(), v.to_string());
    }
    if a.pe {
        m.insert("pe".to_string(), "1".to_string());
    }
    if a.vm_read {
        m.insert("vm_read".to_string(), "1".to_string());
    }
    if a.enumerate {
        m.insert("enum".to_string(), "1".to_string());
    }
    m
}

fn pb_key(k: &NodeKey) -> pb::NodeKey {
    let key = match k {
        NodeKey::Process { pid, start_ts } => {
            pb::node_key::Key::Process(pb::ProcessKey { pid: *pid, start_ts: *start_ts })
        }
        NodeKey::File { file_id } => pb::node_key::Key::File(pb::FileKey { file_id: file_id.clone() }),
        NodeKey::Socket { key } => pb::node_key::Key::Socket(pb::SocketKey { key: key.clone() }),
        NodeKey::Other { kind, key } => {
            pb::node_key::Key::Other(pb::OtherKey { kind: kind.clone(), key: key.clone() })
        }
    };
    pb::NodeKey { key: Some(key) }
}

fn pb_op(op: Op) -> pb::Op {
    match op {
        Op::Exec => pb::Op::Exec,
        Op::Open => pb::Op::Open,
        Op::Read => pb::Op::Read,
        Op::Write => pb::Op::Write,
        Op::Connect => pb::Op::Connect,
        Op::Inject => pb::Op::Inject,
        Op::Create => pb::Op::Create,
        Op::Delete => pb::Op::Delete,
        Op::Load => pb::Op::Load,
        Op::Dup => pb::Op::Dup,
    }
}

// ---- pb → edr_engine::wire (with validation) --------------------------------

fn wire_from_pb(m: pb::Wire) -> Result<Wire, String> {
    match m.msg {
        Some(pb::wire::Msg::Event(we)) => Ok(Wire::Event(WireEvent {
            seq: we.seq,
            endpoint_sid: we.endpoint_sid as usize,
            ttps: we.ttps,
            event: event_from_pb(we.event.ok_or("WireEvent: missing event")?)?,
        })),
        Some(pb::wire::Msg::Block(br)) => Ok(Wire::Block(BlockReport {
            seq: br.seq,
            pattern: br.pattern,
            score: br.score,
            reason: br.reason,
            event: event_from_pb(br.event.ok_or("BlockReport: missing event")?)?,
        })),
        None => Err("Wire: missing oneof msg".to_string()),
    }
}

fn event_from_pb(e: pb::Event) -> Result<Event, String> {
    let mut attrs = Attrs::default();
    for (k, v) in e.attrs {
        attrs.set(&k, v);
    }
    Ok(Event {
        ts: e.ts,
        op: op_from_pb(e.op)?,
        actor: key_from_pb(e.actor.ok_or("Event: missing actor")?)?,
        object: key_from_pb(e.object.ok_or("Event: missing object")?)?,
        attrs,
    })
}

fn key_from_pb(k: pb::NodeKey) -> Result<NodeKey, String> {
    Ok(match k.key.ok_or("NodeKey: missing oneof key")? {
        pb::node_key::Key::Process(p) => NodeKey::Process { pid: p.pid, start_ts: p.start_ts },
        pb::node_key::Key::File(f) => NodeKey::File { file_id: f.file_id },
        pb::node_key::Key::Socket(s) => NodeKey::Socket { key: s.key },
        pb::node_key::Key::Other(o) => NodeKey::Other { kind: o.kind, key: o.key },
    })
}

fn op_from_pb(code: i32) -> Result<Op, String> {
    Ok(match pb::Op::try_from(code) {
        Ok(pb::Op::Exec) => Op::Exec,
        Ok(pb::Op::Open) => Op::Open,
        Ok(pb::Op::Read) => Op::Read,
        Ok(pb::Op::Write) => Op::Write,
        Ok(pb::Op::Connect) => Op::Connect,
        Ok(pb::Op::Inject) => Op::Inject,
        Ok(pb::Op::Create) => Op::Create,
        Ok(pb::Op::Delete) => Op::Delete,
        Ok(pb::Op::Load) => Op::Load,
        Ok(pb::Op::Dup) => Op::Dup,
        Ok(pb::Op::Unspecified) | Err(_) => {
            return Err(format!("Op: value {} not valid on the wire", code))
        }
    })
}
